name: Ultimate_BlockRegeneration
version: '2.0.49'
main: org.hmmbo.ultimate_blockregeneration.Ultimate_BlockRegeneration
api-version: '1.17'
load: POSTWORLD
commands:
  regen:
softdepend:
  - Vault
  - ItemsAdder
  - Oraxen
  - PlaceholderAPI
  - Nexo
  - Scyther

