name: SeriaFarm
version: 1.2.1
main: id.seria.farm.SeriaFarmPlugin
api-version: '1.21'
depend: [MMOItems, AuraSkills, WorldGuard, SeriaCore]
commands:
  sfarm:
    description: Main command for SeriaFarm
    aliases: [seriafarm]
    permission: seriafarm.use
permissions:
  seriafarm.admin:
    description: Full access to SeriaFarm
    default: op
  seriafarm.use:
    description: Access to player commands
    default: true
