# SeriaFarm General Configuration
settings:
  database-type: SQLITE
  debug: true
  action-bar: true
  show-growth-actionbar: true
  harvest-click: true # Right-click to harvest
  worldguard-bypass: true
  # Growth Settings
  # INSTANT: Block restores immediately after delay (default for most blocks)
  # VANILLA: Block grows in phases (Ageable crops, Amethyst, Bamboo)
  crop-growth-mode: VANILLA

# Integration settings
hooks:
  mmoitems: true
  auraskills: true
  itemsadder: true
  oraxen: true
  nexo: true
